# personal data cleaning

In [1]:
import pandas as pd

In [36]:
df1=pd.read_csv(r"C:\Users\USER\Downloads\train.csv")

In [20]:
df1

,PassengerId,Survived,Pclass,Full_name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,Mr. Owen Harris Braund,male,22,1,0,A521171,7.2500,S
1,2,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cu...,female,38,1,0,PC17599,71.2833,C
2,3,1,3,Miss. Laina Heikkinen,female,26,0,0,STONO23101282,7.9250,S
3,4,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35,1,0,113803,53.1000,S
4,5,0,3,Mr. William Henry Allen,male,35,0,0,373450,8.0500,S
6,7,0,1,Mr. Timothy J McCarthy,male,54,0,0,17463,51.8625,S
7,8,0,3,Master. Gosta Leonard Palsson,male,2,3,1,349909,21.0750,S
8,9,1,3,Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson,female,27,0,2,347742,11.1333,S
9,10,1,2,Mrs. Nicholas (Adele Achem) Nasser,female,14,1,0,237736,30.0708,C
10,11,1,3,Miss. Marguerite Rut Sandstrom,female,4,1,1,PP9549,16.7000,S
11,12,1,1,Miss. Elizabeth Bonnell,female,58,0,0,113783,26.5500,S
12,13,0,3,Mr. William Henry Saundercock,male,20,0,0,A52151,8.0500,S
13,14,0,3,Mr. Anders Johan Andersson,male,39,1,5,347082,31.2750,S
14,15,0,3,Miss. Hulda Amanda Adolfina Vestrom,female,14,0,0,350406,7.8542,S
15,16,1,2,Mrs. (Mary D Kingcome) Hewlett,female,55,0,0,248706,16.0000,S
16,17,0,3,Master. Eugene Rice,male,2,4,1,382652,29.1250,Q
18,19,0,3,Mrs. Julius (Emelia Maria Vandemoortele) Vand...,female,31,1,0,345763,18.0000,S
20,21,0,2,Mr. Joseph J Fynney,male,35,0,0,239865,26.0000,S
21,22,1,2,Mr. Lawrence Beesley,male,34,0,0,248698,13.0000,S
22,23,1,3,"Miss. Anna ""Annie"" McGowan",female,15,0,0,330923,8.0292,Q
23,24,1,1,Mr. William Thompson Sloper,male,28,0,0,113788,35.5000,S
24,25,0,3,Miss. Torborg Danira Palsson,female,8,3,1,349909,21.0750,S
25,26,1,3,Mrs. Carl Oscar (Selma Augusta Emilia Johanss...,female,38,1,5,347077,31.3875,S
27,28,0,1,Mr. Charles Alexander Fortune,male,19,3,2,19950,263.0000,S
30,31,0,1,Don. Manuel E Uruchurtu,male,40,0,0,PC17601,27.7208,C
33,34,0,2,Mr. Edward H Wheadon,male,66,0,0,CA24579,10.5000,S
34,35,0,1,Mr. Edgar Joseph Meyer,male,28,1,0,PC17604,82.1708,C
35,36,0,1,Mr. Alexander Oskar Holverson,male,42,1,0,113789,52.0000,S
37,38,0,3,Mr. Ernest Charles Cann,male,21,0,0,A52152,8.0500,S
38,39,0,3,Miss. Augusta Maria Vander Planke,female,18,2,0,345764,18.0000,S
39,40,1,3,Miss. Jamila Nicola-Yarred,female,14,1,0,2651,11.2417,C
40,41,0,3,Mrs. Johan (Johanna Persdotter Larsson) Ahlin,female,40,1,0,7546,9.4750,S
41,42,0,2,Mrs. William John Robert (Dorothy Ann Wonnaco...,female,27,1,0,11668,21.0000,S
43,44,1,2,Miss. Simonne Marie Anne Andree Laroche,female,3,1,2,SCParis2123,41.5792,C
44,45,1,3,Miss. Margaret Delia Devaney,female,19,0,0,330958,7.8792,Q
49,50,0,3,Mrs. Josef (Josefine Franchi) Arnold-Franchi,female,18,1,0,349237,17.8000,S
50,51,0,3,Master. Juha Niilo Panula,male,7,4,1,3101295,39.6875,S
51,52,0,3,Mr. Richard Cater Nosworthy,male,21,0,0,A439886,7.8000,S
52,53,1,1,Mrs. Henry Sleeper (Myna Haxtun) Harper,female,49,1,0,PC17572,76.7292,C
53,54,1,2,Mrs. Lizzie (Elizabeth Anne Wilkinson) Faunth...,female,29,1,0,2926,26.0000,S
54,55,0,1,Mr. Engelhart Cornelius Ostby,male,65,0,1,113509,61.9792,C
56,57,1,2,Miss. Emily Rugg,female,21,0,0,CA31026,10.5000,S
57,58,0,3,Mr. Mansouer Novel,male,28,0,0,2697,7.2292,C
58,59,1,2,Miss. Constance Mirium West,female,5,1,2,CA34651,27.7500,S
59,60,0,3,Master. William Frederick Goodwin,male,11,5,2,CA2144,46.9000,S
60,61,0,3,Mr. Orsen Sirayanian,male,22,0,0,2669,7.2292,C
61,62,1,1,Miss. Amelie Icard,female,38,0,0,113572,80.0000,NaN
62,63,0,1,Mr. Henry Birkhardt Harris,male,45,1,0,36973,83.4750,S
63,64,0,3,Master. Harald Skoog,male,4,3,2,347088,27.9000,S
66,67,1,2,Mrs. (Elizabeth Ramell) Nye,female,29,0,0,CA29395,10.5000,S
67,68,0,3,Mr. Ernest James Crease,male,19,0,0,SP3464,8.1583,S
68,69,1,3,Miss. Erna Alexandra Andersson,female,17,4,2,3101281,7.9250,S
69,70,0,3,Mr. Vincenz Kink,male,26,2,0,315151,8.6625,S
70,71,0,2,Mr. Stephen Curnow Jenkin,male,32,0,0,CA33111,10.5000,S
71,72,0,3,Miss. Lillian Amy Goodwin,female,16,5,2,CA2144,46.9000,S
72,73,0,2,Mr. Ambrose Jr Hood,male,21,0,0,SOC14879,73.5000,S
73,74,0,3,Mr. Apostolos Chronopoulos,male,26,1,0,2680,14.4542,C
74,75,1,3,Mr. Lee Bing,male,32,0,0,1601,56.4958,S
75,76,0,3,Mr. Sigurd Hansen Moen,male,25,0,0,348123,7.6500,S
79,80,1,3,Miss. Elizabeth Dowdell,female,30,0,0,364516,12.4750,S
80,81,0,3,Mr. Achille Waelens,male,22,0,0,345767,9.0000,S
81,82,1,3,Mr. Jan Baptist Sheerlinck,male,29,0,0,345779,9.5000,S
83,84,0,1,Mr. Francisco M Carrau,male,28,0,0,113059,47.1000,S
84,85,1,2,Miss. Bertha Ilett,female,17,0,0,SOC14885,10.5000,S
85,86,1,3,Mrs. Karl Alfred (Maria Mathilda Gustafsson) ...,female,33,3,0,3101278,15.8500,S
86,87,0,3,Mr. William Neal Ford,male,16,1,3,WC6608,34.3750,S
88,89,1,1,Miss. Mabel Helen Fortune,female,23,3,2,19950,263.0000,S
89,90,0,3,Mr. Francesco Celotti,male,24,0,0,343275,8.0500,S
90,91,0,3,Mr. Emil Christmann,male,29,0,0,343276,8.0500,S
91,92,0,3,Mr. Paul Edvin Andreasson,male,20,0,0,347466,7.8542,S
92,93,0,1,Mr. Herbert Fuller Chaffee,male,46,1,0,WEP5734,61.1750,S
93,94,0,3,Mr. Bertram Frank Dean,male,26,1,2,CA2315,20.5750,S
94,95,0,3,Mr. Daniel Coxon,male,59,0,0,364500,7.2500,S
96,97,0,1,Mr. George B Goldschmidt,male,71,0,0,PC17754,34.6542,C
97,98,1,1,Mr. William Bertram Greenfield,male,23,0,1,PC17759,63.3583,C
98,99,1,2,Mrs. John T (Ada Julia Bone) Doling,female,34,0,1,231919,23.0000,S
99,100,0,2,Mr. Sinai Kantor,male,34,1,0,244367,26.0000,S
100,101,0,3,Miss. Matilda Petranec,female,28,0,0,349245,7.8958,S
102,103,0,1,Mr. Richard Frasar White,male,21,0,1,35281,77.2875,S
103,104,0,3,Mr. Gustaf Joel Johansson,male,33,0,0,7540,8.6542,S
104,105,0,3,Mr. Anders Vilhelm Gustafsson,male,37,2,0,3101276,7.9250,S
105,106,0,3,Mr. Stoytcho Mionoff,male,28,0,0,349207,7.8958,S
106,107,1,3,Miss. Anna Kristine Salkjelsvik,female,21,0,0,343120,7.6500,S
108,109,0,3,Mr. Tido Rekic,male,38,0,0,349249,7.8958,S
110,111,0,1,Mr. Walter Chamberlain Porter,male,47,0,0,110465,52.0000,S
111,112,0,3,Miss. Hileni Zabour,female,14,1,0,2665,14.4542,C
112,113,0,3,Mr. David John Barton,male,22,0,0,324669,8.0500,S
113,114,0,3,Miss. Katriina Jussila,female,20,1,0,4136,9.8250,S
114,115,0,3,Miss. Malake Attalah,female,17,0,0,2627,14.4583,C
115,116,0,3,Mr. Edvard Pekoniemi,male,21,0,0,STONO23101294,7.9250,S
116,117,0,3,Mr. Patrick Connors,male,70,0,0,370369,7.7500,Q
117,118,0,2,Mr. William John Robert Turpin,male,29,1,0,11668,21.0000,S
118,119,0,1,Mr. Quigg Edmond Baxter,male,24,0,1,PC17558,247.5208,C
119,120,0,3,Miss. Ellis Anna Maria Andersson,female,2,4,2,347082,31.2750,S
120,121,0,2,Mr. Stanley George Hickman,male,21,2,0,SOC14879,73.5000,S
122,123,0,2,Mr. Nicholas Nasser,male,32,1,0,237736,30.0708,C
123,124,1,2,Miss. Susan Webber,female,32,0,0,27267,13.0000,S
124,125,0,1,Mr. Percival Wayland White,male,54,0,1,35281,77.2875,S
125,126,1,3,Master. Elias Nicola-Yarred,male,12,1,0,2651,11.2417,C
127,128,1,3,Mr. Fridtjof Arne Madsen,male,24,0,0,C17369,7.1417,S
129,130,0,3,Mr. Johan Ekstrom,male,45,0,0,347061,6.9750,S
130,131,0,3,Mr. Jozef Drazenoic,male,33,0,0,349241,7.8958,C
131,132,0,3,Mr. Domingos Fernandeo Coelho,male,20,0,0,SOTONOQ3101307,7.0500,S
132,133,0,3,Mrs. Alexander A (Grace Charity Laury) Robins,female,47,1,0,A53337,14.5000,S
133,134,1,2,Mrs. Leopold (Mathilde Francoise Pede) Weisz,female,29,1,0,228414,26.0000,S
134,135,0,2,Mr. Samuel James Hayden Sobey,male,25,0,0,CA29178,13.0000,S
135,136,0,2,Mr. Emile Richard,male,23,0,0,SCPARIS2133,15.0458,C
136,137,1,1,Miss. Helen Monypeny Newsom,female,19,0,2,11752,26.2833,S
137,138,0,1,Mr. Jacques Heath Futrelle,male,37,1,0,113803,53.1000,S
138,139,0,3,Mr. Olaf Elon Osen,male,16,0,0,7534,9.2167,S
139,140,0,1,Mr. Victor Giglio,male,24,0,0,PC17593,79.2000,C
141,142,1,3,Miss. Anna Sofia Nysten,female,22,0,0,347081,7.7500,S
142,143,1,3,Mrs. Pekka Pietari (Elin Matilda Dolck) Hakka...,female,24,1,0,STONO23101279,15.8500,S
143,144,0,3,Mr. Jeremiah Burke,male,19,0,0,365222,6.7500,Q
144,145,0,2,Mr. Edgardo Samuel Andrew,male,18,0,0,231945,11.5000,S
145,146,0,2,Mr. Joseph Charles Nicholls,male,19,1,1,CA33112,36.7500,S
146,147,1,3,"Mr. August Edvard (""Wennerstrom"") Andersson",male,27,0,0,350043,7.7958,S
147,148,0,3,"Miss. Robina Maggie ""Ruby"" Ford",female,9,2,2,WC6608,34.3750,S
148,149,0,2,"Mr. Michel (""Louis M Hoffman"") Navratil",male,36,0,2,230080,26.0000,S
149,150,0,2,Rev. Thomas Roussel Davids Byles,male,42,0,0,244310,13.0000,S
150,151,0,2,Rev. Robert James Bateman,male,51,0,0,SOP1166,12.5250,S
151,152,1,1,Mrs. Thomas (Edith Wearne) Pears,female,22,1,0,113776,66.6000,S
152,153,0,3,Mr. Alfonzo Meo,male,55,0,0,A511206,8.0500,S
153,154,0,3,Mr. Austin Blyler van Billiard,male,40,0,2,A5851,14.5000,S
155,156,0,1,Mr. Charles Duane Williams,male,51,0,1,PC17597,61.3792,C
156,157,1,3,"Miss. Katherine ""Katie"" Gilnagh",female,16,0,0,35851,7.7333,Q
157,158,0,3,Mr. Harry Corn,male,30,0,0,SOTONOQ392090,8.0500,S
160,161,0,3,Mr. John Hatfield Cribb,male,44,0,1,371362,16.1000,S
161,162,1,2,"Mrs. James (Elizabeth ""Bessie"" Inglis Milne) ...",female,40,0,0,CA33595,15.7500,S
162,163,0,3,Mr. John Viktor Bengtsson,male,26,0,0,347068,7.7750,S
163,164,0,3,Mr. Jovo Calic,male,17,0,0,315093,8.6625,S
164,165,0,3,Master. Eino Viljami Panula,male,1,4,1,3101295,39.6875,S
165,166,1,3,"Master. Frank John William ""Frankie"" Goldsmith",male,9,0,2,363291,20.5250,S
167,168,0,3,Mrs. William (Anna Bernhardina Karlsson) Skoog,female,45,1,4,347088,27.9000,S
169,170,0,3,Mr. Lee Ling,male,28,0,0,1601,56.4958,S
170,171,0,1,Mr. Wyckoff Van der hoef,male,61,0,0,111240,33.5000,S
171,172,0,3,Master. Arthur Rice,male,4,4,1,382652,29.1250,Q
172,173,1,3,Miss. Eleanor Ileen Johnson,female,1,1,1,347742,11.1333,S
173,174,0,3,Mr. Antti Wilhelm Sivola,male,21,0,0,STONO23101280,7.9250,S
174,175,0,1,Mr. James Clinch Smith,male,56,0,0,17764,30.6958,C
175,176,0,3,Mr. Klas Albin Klasen,male,18,1,1,350404,7.8542,S
177,178,0,1,Miss. Ann Elizabeth Isham,female,50,0,0,PC17595,28.7125,C
178,179,0,2,Mr. Reginald Hale,male,30,0,0,250653,13.0000,S
179,180,0,3,Mr. Lionel Leonard,male,36,0,0,LINE,0.0000,S
182,183,0,3,Master. Clarence Gustaf Hugo Asplund,male,9,4,2,347077,31.3875,S
183,184,1,2,Master. Richard F Becker,male,1,2,1,230136,39.0000,S
184,185,1,3,Miss. Luise Gretchen Kink-Heilmann,female,4,0,2,315153,22.0250,S
187,188,1,1,"Mr. Charles Hallace (""Mr C Rolmane"") Romaine",male,45,0,0,111428,26.5500,S
188,189,0,3,Mr. John Bourke,male,40,1,1,364849,15.5000,Q
189,190,0,3,Mr. Stjepan Turcin,male,36,0,0,349247,7.8958,S
190,191,1,2,Mrs. (Rosa) Pinsky,female,32,0,0,234604,13.0000,S
191,192,0,2,Mr. William Carbines,male,19,0,0,28424,13.0000,S
192,193,1,3,Miss. Carla Christine Nielsine Andersen-Jensen,female,19,1,0,350046,7.8542,S
193,194,1,2,Master. Michel M Navratil,male,3,1,1,230080,26.0000,S
194,195,1,1,Mrs. James Joseph (Margaret Tobin) Brown,female,44,0,0,PC17610,27.7208,C
195,196,1,1,Miss. Elise Lurette,female,58,0,0,PC17569,146.5208,C
197,198,0,3,Mr. Karl Siegwart Andreas Olsen,male,42,0,1,4579,8.4042,S
199,200,0,2,"Miss. Henriette (""Mrs Harbeck"") Yrois",female,24,0,0,248747,13.0000,S
200,201,0,3,Mr. Nestor Cyriel Vande Walle,male,28,0,0,345770,9.5000,S
202,203,0,3,Mr. Jakob Alfred Johanson,male,34,0,0,3101264,6.4958,S
203,204,0,3,Mr. Gerious Youseff,male,45,0,0,2628,7.2250,C
204,205,1,3,"Mr. Gurshon ""Gus"" Cohen",male,18,0,0,A53540,8.0500,S
205,206,0,3,Miss. Telma Matilda Strom,female,2,0,1,347054,10.4625,S
206,207,0,3,Mr. Karl Alfred Backstrom,male,32,1,0,3101278,15.8500,S
207,208,1,3,Mr. Nassef Cassem Albimona,male,26,0,0,2699,18.7875,C
208,209,1,3,"Miss. Helen ""Ellen"" Carr",female,16,0,0,367231,7.7500,Q
209,210,1,1,Mr. Henry Blank,male,40,0,0,112277,31.0000,C
210,211,0,3,Mr. Ahmed Ali,male,24,0,0,SOTONOQ3101311,7.0500,S
211,212,1,2,Miss. Clear Annie Cameron,female,35,0,0,FCC13528,21.0000,S
212,213,0,3,Mr. John Henry Perkin,male,22,0,0,A521174,7.2500,S
213,214,0,2,Mr. Hans Kristensen Givard,male,30,0,0,250646,13.0000,S
215,216,1,1,Miss. Madeleine Newell,female,31,1,0,35273,113.2750,C
216,217,1,3,Miss. Eliina Honkanen,female,27,0,0,STONO23101283,7.9250,S
217,218,0,2,Mr. Sidney Samuel Jacobsohn,male,42,1,0,243847,27.0000,S
218,219,1,1,Miss. Albina Bazzani,female,32,0,0,11813,76.2917,C
219,220,0,2,Mr. Walter Harris,male,30,0,0,WC14208,10.5000,S
220,221,1,3,Mr. Victor Francis Sunderland,male,16,0,0,SOTONOQ392089,8.0500,S
221,222,0,2,Mr. James H Bracken,male,27,0,0,220367,13.0000,S
222,223,0,3,Mr. George Henry Green,male,51,0,0,21440,8.0500,S
224,225,1,1,Mr. Frederick Maxfield Hoyt,male,38,1,0,19943,90.0000,S
225,226,0,3,Mr. Karl Ivar Sven Berglund,male,22,0,0,PP4348,9.3500,S
226,227,1,2,Mr. William John Mellors,male,19,0,0,SWPP751,10.5000,S
227,228,0,3,"Mr. John Hall (""Henry"") Lovell",male,20,0,0,A521173,7.2500,S
228,229,0,2,Mr. Arne Jonas Fahlstrom,male,18,0,0,236171,13.0000,S
230,231,1,1,Mrs. Henry Birkhardt (Irene Wallach) Harris,female,35,1,0,36973,83.4750,S
231,232,0,3,Mr. Bengt Edvin Larsson,male,29,0,0,347067,7.7750,S
232,233,0,2,Mr. Ernst Adolf Sjostedt,male,59,0,0,237442,13.5000,S
233,234,1,3,Miss. Lillian Gertrud Asplund,female,5,4,2,347077,31.3875,S
234,235,0,2,Mr. Robert William Norman Leyson,male,24,0,0,CA29566,10.5000,S
236,237,0,2,Mr. Stephen Hold,male,44,1,0,26707,26.0000,S
237,238,1,2,"Miss. Marjorie ""Lottie"" Collyer",female,8,0,2,CA31921,26.2500,S
238,239,0,2,Mr. Frederick William Pengelly,male,19,0,0,28665,10.5000,S
239,240,0,2,Mr. George Henry Hunt,male,33,0,0,SCOW1585,12.2750,S
242,243,0,2,Mr. Reginald Charles Coleridge,male,29,0,0,WC14263,10.5000,S
243,244,0,3,Mr. Matti Alexanteri Maenpaa,male,22,0,0,STONO23101275,7.1250,S
244,245,0,3,Mr. Sleiman Attalah,male,30,0,0,2694,7.2250,C
245,246,0,1,Dr. William Edward Minahan,male,44,2,0,19928,90.0000,Q
246,247,0,3,Miss. Agda Thorilda Viktoria Lindahl,female,25,0,0,347071,7.7750,S
247,248,1,2,Mrs. William (Anna) Hamalainen,female,24,0,2,250649,14.5000,S
248,249,1,1,Mr. Richard Leonard Beckwith,male,37,1,1,11751,52.5542,S
249,250,0,2,Rev. Ernest Courtenay Carter,male,54,1,0,244252,26.0000,S
251,252,0,3,Mrs. Wilhelm (Elna Matilda Persson) Strom,female,29,1,1,347054,10.4625,S
252,253,0,1,Mr. William Thomas Stead,male,62,0,0,113514,26.5500,S
253,254,0,3,Mr. William Arthur Lobb,male,30,1,0,A53336,16.1000,S
254,255,0,3,Mrs. Viktor (Helena Wilhelmina) Rosblom,female,41,0,2,370129,20.2125,S
255,256,1,3,Mrs. Darwis (Hanne Youssef Razi) Touma,female,29,0,2,2650,15.2458,C
257,258,1,1,Miss. Gladys Cherry,female,30,0,0,110152,86.5000,S
258,259,1,1,Miss. Anna Ward,female,35,0,0,PC17755,512.3292,C
259,260,1,2,Mrs. (Lutie Davis) Parrish,female,50,0,1,230433,26.0000,S
261,262,1,3,Master. Edvin Rojj Felix Asplund,male,3,4,2,347077,31.3875,S
262,263,0,1,Mr. Emil Taussig,male,52,1,1,110413,79.6500,S
263,264,0,1,Mr. William Harrison,male,40,0,0,112059,0.0000,S
265,266,0,2,Mr. David Reeves,male,36,0,0,CA17248,10.5000,S
266,267,0,3,Mr. Ernesti Arvid Panula,male,16,4,1,3101295,39.6875,S
267,268,1,3,Mr. Ernst Ulrik Persson,male,25,1,0,347083,7.7750,S
268,269,1,1,Mrs. William Thompson (Edith Junkins) Graham,female,58,0,1,PC17582,153.4625,S
269,270,1,1,Miss. Amelia Bissette,female,35,0,0,PC17760,135.6333,S
271,272,1,3,Mr. William Henry Tornquist,male,25,0,0,LINE,0.0000,S
272,273,1,2,Mrs. (Elizabeth Anne Maidment) Mellinger,female,41,0,1,250644,19.5000,S
273,274,0,1,Mr. Charles H Natsch,male,37,0,1,PC17596,29.7000,C
275,276,1,1,Miss. Kornelia Theodosia Andrews,female,63,1,0,13502,77.9583,S
276,277,0,3,Miss. Augusta Charlotta Lindblom,female,45,0,0,347073,7.7500,S
278,279,0,3,Master. Eric Rice,male,7,4,1,382652,29.1250,Q
279,280,1,3,Mrs. Stanton (Rosa Hunt) Abbott,female,35,1,1,CA2673,20.2500,S
280,281,0,3,Mr. Frank Duane,male,65,0,0,336439,7.7500,Q
281,282,0,3,Mr. Nils Johan Goransson Olsson,male,28,0,0,347464,7.8542,S
282,283,0,3,Mr. Alfons de Pelsmaeker,male,16,0,0,345778,9.5000,S
283,284,1,3,Mr. Edward Arthur Dorking,male,19,0,0,A510482,8.0500,S
285,286,0,3,Mr. Ivan Stankovic,male,33,0,0,349239,8.6625,C
286,287,1,3,Mr. Theodore de Mulder,male,30,0,0,345774,9.5000,S
287,288,0,3,Mr. Penko Naidenoff,male,22,0,0,349206,7.8958,S
288,289,1,2,Mr. Masabumi Hosono,male,42,0,0,237798,13.0000,S
289,290,1,3,Miss. Kate Connolly,female,22,0,0,370373,7.7500,Q
290,291,1,1,"Miss. Ellen ""Nellie"" Barber",female,26,0,0,19877,78.8500,S
291,292,1,1,Mrs. Dickinson H (Helen Walton) Bishop,female,19,1,0,11967,91.0792,C
292,293,0,2,Mr. Rene Jacques Levy,male,36,0,0,SCParis2163,12.8750,C
293,294,0,3,Miss. Aloisia Haas,female,24,0,0,349236,8.8500,S
294,295,0,3,Mr. Ivan Mineff,male,24,0,0,349233,7.8958,S
296,297,0,3,Mr. Mansour Hanna,male,23,0,0,2693,7.2292,C
297,298,0,1,Miss. Helen Loraine Allison,female,2,1,2,113781,151.5500,S
299,300,1,1,Mrs. James (Helene DeLaudeniere Chaput) Baxter,female,50,0,1,PC17558,247.5208,C
302,303,0,3,Mr. William Cahoone Jr Johnson,male,19,0,0,LINE,0.0000,S
307,308,1,1,Mrs. Victor de Satode (Maria Josefa Perez de ...,female,17,1,0,PC17758,108.9000,C
308,309,0,2,Mr. Samuel Abelson,male,30,1,0,PPP3381,24.0000,C
309,310,1,1,Miss. Laura Mabel Francatelli,female,30,0,0,PC17485,56.9292,C
310,311,1,1,Miss. Margaret Bechstein Hays,female,24,0,0,11767,83.1583,C
311,312,1,1,Miss. Emily Borie Ryerson,female,18,2,2,PC17608,262.3750,C
312,313,0,2,Mrs. William (Anna Sylfven) Lahtinen,female,26,1,1,250651,26.0000,S
313,314,0,3,Mr. Ignjac Hendekovic,male,28,0,0,349243,7.8958,S
314,315,0,2,Mr. Benjamin Hart,male,43,1,1,FCC13529,26.2500,S
315,316,1,3,Miss. Helmina Josefina Nilsson,female,26,0,0,347470,7.8542,S
316,317,1,2,Mrs. Sinai (Miriam Sternin) Kantor,female,24,1,0,244367,26.0000,S
317,318,0,2,Dr. Ernest Moraweck,male,54,0,0,29011,14.0000,S
318,319,1,1,Miss. Mary Natalie Wick,female,31,0,2,36928,164.8667,S
319,320,1,1,Mrs. Frederic Oakley (Margaretta Corning Ston...,female,40,1,1,16966,134.5000,C
320,321,0,3,Mr. Samuel Dennis,male,22,0,0,A521172,7.2500,S
321,322,0,3,Mr. Yoto Danoff,male,27,0,0,349219,7.8958,S
322,323,1,2,Miss. Hilda Mary Slayter,female,30,0,0,234818,12.3500,Q
323,324,1,2,Mrs. Albert Francis (Sylvia Mae Harbaugh) Cal...,female,22,1,1,248738,29.0000,S
325,326,1,1,Miss. Marie Grice Young,female,36,0,0,PC17760,135.6333,C
326,327,0,3,Mr. Johan Hansen Nysveen,male,61,0,0,345364,6.2375,S
327,328,1,2,Mrs. (Ada E Hall) Ball,female,36,0,0,28551,13.0000,S
328,329,1,3,Mrs. Frank John (Emily Alice Brown) Goldsmith,female,31,1,1,363291,20.5250,S
329,330,1,1,Miss. Jean Gertrude Hippach,female,16,0,1,111361,57.9792,C
331,332,0,1,Mr. Austen Partner,male,45,0,0,113043,28.5000,S
332,333,0,1,Mr. George Edward Graham,male,38,0,1,PC17582,153.4625,S
333,334,0,3,Mr. Leo Edmondus Vander Planke,male,16,2,0,345764,18.0000,S
336,337,0,1,Mr. Thomas Clinton Pears,male,29,1,0,113776,66.6000,S
337,338,1,1,Miss. Elizabeth Margaret Burns,female,41,0,0,16966,134.5000,C
338,339,1,3,Mr. Karl Edwart Dahl,male,45,0,0,7598,8.0500,S
339,340,0,1,Mr. Stephen Weart Blackwell,male,45,0,0,113784,35.5000,S
340,341,1,2,Master. Edmond Roger Navratil,male,2,1,1,230080,26.0000,S
341,342,1,1,Miss. Alice Elizabeth Fortune,female,24,3,2,19950,263.0000,S
342,343,0,2,Mr. Erik Gustaf Collander,male,28,0,0,248740,13.0000,S
343,344,0,2,Mr. Charles Frederick Waddington Sedgwick,male,25,0,0,244361,13.0000,S
344,345,0,2,Mr. Stanley Hubert Fox,male,36,0,0,229236,13.0000,S
345,346,1,2,"Miss. Amelia ""Mildred"" Brown",female,24,0,0,248733,13.0000,S
346,347,1,2,Miss. Marion Elsie Smith,female,40,0,0,31418,13.0000,S
348,349,1,3,"Master. William Loch ""William"" Coutts",male,3,1,1,CA37671,15.9000,S
349,350,0,3,Mr. Jovan Dimic,male,42,0,0,315088,8.6625,S
350,351,0,3,Mr. Nils Martin Odahl,male,23,0,0,7267,9.2250,S
352,353,0,3,Mr. Tannous Elias,male,15,1,1,2695,7.2292,C
353,354,0,3,Mr. Josef Arnold-Franchi,male,25,1,0,349237,17.8000,S
355,356,0,3,Mr. Leo Peter Vanden Steen,male,28,0,0,345783,9.5000,S
356,357,1,1,Miss. Elsie Edith Bowerman,female,22,0,1,113505,55.0000,S
357,358,0,2,Miss. Annie Clemmer Funk,female,38,0,0,237671,13.0000,S
360,361,0,3,Mr. Wilhelm Skoog,male,40,1,4,347088,27.9000,S
361,362,0,2,Mr. Sebastiano del Carlo,male,29,1,0,SCPARIS2167,27.7208,C
362,363,0,3,Mrs. (Catherine David) Barbara,female,45,0,1,2691,14.4542,C
363,364,0,3,Mr. Adola Asim,male,35,0,0,SOTONOQ3101310,7.0500,S

In [4]:
pd.options.display.max_rows= 891

In [19]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 707 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  707 non-null    int64
 1   Survived     707 non-null    int64
 2   Pclass       707 non-null    int64
 3   Full_name    707 non-null    object
 4   Sex          707 non-null    object
 5   Age          707 non-null    int64
 6   SibSp        707 non-null    int64
 7   Parch        707 non-null    int64
 8   Ticket       707 non-null    object
 9   Fare         707 non-null    float64
 10  Embarked     705 non-null    object
dtypes: float64(1), int64(6), object(4)
memory usage: 66.3+ KB

In [21]:
df1.duplicated().sum()

np.int64(0)

In [34]:
df1=df1.drop_duplicates()
df1

,PassengerId,Survived,Pclass,Full_name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,Mr. Owen Harris Braund,male,22,1,0,A521171,7.2500,S
1,2,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cu...,female,38,1,0,PC17599,71.2833,C
2,3,1,3,Miss. Laina Heikkinen,female,26,0,0,STONO23101282,7.9250,S
3,4,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35,1,0,113803,53.1000,S
4,5,0,3,Mr. William Henry Allen,male,35,0,0,373450,8.0500,S
6,7,0,1,Mr. Timothy J McCarthy,male,54,0,0,17463,51.8625,S
7,8,0,3,Master. Gosta Leonard Palsson,male,2,3,1,349909,21.0750,S
8,9,1,3,Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson,female,27,0,2,347742,11.1333,S
9,10,1,2,Mrs. Nicholas (Adele Achem) Nasser,female,14,1,0,237736,30.0708,C
10,11,1,3,Miss. Marguerite Rut Sandstrom,female,4,1,1,PP9549,16.7000,S
11,12,1,1,Miss. Elizabeth Bonnell,female,58,0,0,113783,26.5500,S
12,13,0,3,Mr. William Henry Saundercock,male,20,0,0,A52151,8.0500,S
13,14,0,3,Mr. Anders Johan Andersson,male,39,1,5,347082,31.2750,S
14,15,0,3,Miss. Hulda Amanda Adolfina Vestrom,female,14,0,0,350406,7.8542,S
15,16,1,2,Mrs. (Mary D Kingcome) Hewlett,female,55,0,0,248706,16.0000,S
16,17,0,3,Master. Eugene Rice,male,2,4,1,382652,29.1250,Q
18,19,0,3,Mrs. Julius (Emelia Maria Vandemoortele) Vand...,female,31,1,0,345763,18.0000,S
20,21,0,2,Mr. Joseph J Fynney,male,35,0,0,239865,26.0000,S
21,22,1,2,Mr. Lawrence Beesley,male,34,0,0,248698,13.0000,S
22,23,1,3,"Miss. Anna ""Annie"" McGowan",female,15,0,0,330923,8.0292,Q
23,24,1,1,Mr. William Thompson Sloper,male,28,0,0,113788,35.5000,S
24,25,0,3,Miss. Torborg Danira Palsson,female,8,3,1,349909,21.0750,S
25,26,1,3,Mrs. Carl Oscar (Selma Augusta Emilia Johanss...,female,38,1,5,347077,31.3875,S
27,28,0,1,Mr. Charles Alexander Fortune,male,19,3,2,19950,263.0000,S
30,31,0,1,Don. Manuel E Uruchurtu,male,40,0,0,PC17601,27.7208,C
33,34,0,2,Mr. Edward H Wheadon,male,66,0,0,CA24579,10.5000,S
34,35,0,1,Mr. Edgar Joseph Meyer,male,28,1,0,PC17604,82.1708,C
35,36,0,1,Mr. Alexander Oskar Holverson,male,42,1,0,113789,52.0000,S
37,38,0,3,Mr. Ernest Charles Cann,male,21,0,0,A52152,8.0500,S
38,39,0,3,Miss. Augusta Maria Vander Planke,female,18,2,0,345764,18.0000,S
39,40,1,3,Miss. Jamila Nicola-Yarred,female,14,1,0,2651,11.2417,C
40,41,0,3,Mrs. Johan (Johanna Persdotter Larsson) Ahlin,female,40,1,0,7546,9.4750,S
41,42,0,2,Mrs. William John Robert (Dorothy Ann Wonnaco...,female,27,1,0,11668,21.0000,S
43,44,1,2,Miss. Simonne Marie Anne Andree Laroche,female,3,1,2,SCParis2123,41.5792,C
44,45,1,3,Miss. Margaret Delia Devaney,female,19,0,0,330958,7.8792,Q
49,50,0,3,Mrs. Josef (Josefine Franchi) Arnold-Franchi,female,18,1,0,349237,17.8000,S
50,51,0,3,Master. Juha Niilo Panula,male,7,4,1,3101295,39.6875,S
51,52,0,3,Mr. Richard Cater Nosworthy,male,21,0,0,A439886,7.8000,S
52,53,1,1,Mrs. Henry Sleeper (Myna Haxtun) Harper,female,49,1,0,PC17572,76.7292,C
53,54,1,2,Mrs. Lizzie (Elizabeth Anne Wilkinson) Faunth...,female,29,1,0,2926,26.0000,S
54,55,0,1,Mr. Engelhart Cornelius Ostby,male,65,0,1,113509,61.9792,C
56,57,1,2,Miss. Emily Rugg,female,21,0,0,CA31026,10.5000,S
57,58,0,3,Mr. Mansouer Novel,male,28,0,0,2697,7.2292,C
58,59,1,2,Miss. Constance Mirium West,female,5,1,2,CA34651,27.7500,S
59,60,0,3,Master. William Frederick Goodwin,male,11,5,2,CA2144,46.9000,S
60,61,0,3,Mr. Orsen Sirayanian,male,22,0,0,2669,7.2292,C
62,63,0,1,Mr. Henry Birkhardt Harris,male,45,1,0,36973,83.4750,S
63,64,0,3,Master. Harald Skoog,male,4,3,2,347088,27.9000,S
66,67,1,2,Mrs. (Elizabeth Ramell) Nye,female,29,0,0,CA29395,10.5000,S
67,68,0,3,Mr. Ernest James Crease,male,19,0,0,SP3464,8.1583,S
68,69,1,3,Miss. Erna Alexandra Andersson,female,17,4,2,3101281,7.9250,S
69,70,0,3,Mr. Vincenz Kink,male,26,2,0,315151,8.6625,S
70,71,0,2,Mr. Stephen Curnow Jenkin,male,32,0,0,CA33111,10.5000,S
71,72,0,3,Miss. Lillian Amy Goodwin,female,16,5,2,CA2144,46.9000,S
72,73,0,2,Mr. Ambrose Jr Hood,male,21,0,0,SOC14879,73.5000,S
73,74,0,3,Mr. Apostolos Chronopoulos,male,26,1,0,2680,14.4542,C
74,75,1,3,Mr. Lee Bing,male,32,0,0,1601,56.4958,S
75,76,0,3,Mr. Sigurd Hansen Moen,male,25,0,0,348123,7.6500,S
79,80,1,3,Miss. Elizabeth Dowdell,female,30,0,0,364516,12.4750,S
80,81,0,3,Mr. Achille Waelens,male,22,0,0,345767,9.0000,S
81,82,1,3,Mr. Jan Baptist Sheerlinck,male,29,0,0,345779,9.5000,S
83,84,0,1,Mr. Francisco M Carrau,male,28,0,0,113059,47.1000,S
84,85,1,2,Miss. Bertha Ilett,female,17,0,0,SOC14885,10.5000,S
85,86,1,3,Mrs. Karl Alfred (Maria Mathilda Gustafsson) ...,female,33,3,0,3101278,15.8500,S
86,87,0,3,Mr. William Neal Ford,male,16,1,3,WC6608,34.3750,S
88,89,1,1,Miss. Mabel Helen Fortune,female,23,3,2,19950,263.0000,S
89,90,0,3,Mr. Francesco Celotti,male,24,0,0,343275,8.0500,S
90,91,0,3,Mr. Emil Christmann,male,29,0,0,343276,8.0500,S
91,92,0,3,Mr. Paul Edvin Andreasson,male,20,0,0,347466,7.8542,S
92,93,0,1,Mr. Herbert Fuller Chaffee,male,46,1,0,WEP5734,61.1750,S
93,94,0,3,Mr. Bertram Frank Dean,male,26,1,2,CA2315,20.5750,S
94,95,0,3,Mr. Daniel Coxon,male,59,0,0,364500,7.2500,S
96,97,0,1,Mr. George B Goldschmidt,male,71,0,0,PC17754,34.6542,C
97,98,1,1,Mr. William Bertram Greenfield,male,23,0,1,PC17759,63.3583,C
98,99,1,2,Mrs. John T (Ada Julia Bone) Doling,female,34,0,1,231919,23.0000,S
99,100,0,2,Mr. Sinai Kantor,male,34,1,0,244367,26.0000,S
100,101,0,3,Miss. Matilda Petranec,female,28,0,0,349245,7.8958,S
102,103,0,1,Mr. Richard Frasar White,male,21,0,1,35281,77.2875,S
103,104,0,3,Mr. Gustaf Joel Johansson,male,33,0,0,7540,8.6542,S
104,105,0,3,Mr. Anders Vilhelm Gustafsson,male,37,2,0,3101276,7.9250,S
105,106,0,3,Mr. Stoytcho Mionoff,male,28,0,0,349207,7.8958,S
106,107,1,3,Miss. Anna Kristine Salkjelsvik,female,21,0,0,343120,7.6500,S
108,109,0,3,Mr. Tido Rekic,male,38,0,0,349249,7.8958,S
110,111,0,1,Mr. Walter Chamberlain Porter,male,47,0,0,110465,52.0000,S
111,112,0,3,Miss. Hileni Zabour,female,14,1,0,2665,14.4542,C
112,113,0,3,Mr. David John Barton,male,22,0,0,324669,8.0500,S
113,114,0,3,Miss. Katriina Jussila,female,20,1,0,4136,9.8250,S
114,115,0,3,Miss. Malake Attalah,female,17,0,0,2627,14.4583,C
115,116,0,3,Mr. Edvard Pekoniemi,male,21,0,0,STONO23101294,7.9250,S
116,117,0,3,Mr. Patrick Connors,male,70,0,0,370369,7.7500,Q
117,118,0,2,Mr. William John Robert Turpin,male,29,1,0,11668,21.0000,S
118,119,0,1,Mr. Quigg Edmond Baxter,male,24,0,1,PC17558,247.5208,C
119,120,0,3,Miss. Ellis Anna Maria Andersson,female,2,4,2,347082,31.2750,S
120,121,0,2,Mr. Stanley George Hickman,male,21,2,0,SOC14879,73.5000,S
122,123,0,2,Mr. Nicholas Nasser,male,32,1,0,237736,30.0708,C
123,124,1,2,Miss. Susan Webber,female,32,0,0,27267,13.0000,S
124,125,0,1,Mr. Percival Wayland White,male,54,0,1,35281,77.2875,S
125,126,1,3,Master. Elias Nicola-Yarred,male,12,1,0,2651,11.2417,C
127,128,1,3,Mr. Fridtjof Arne Madsen,male,24,0,0,C17369,7.1417,S
129,130,0,3,Mr. Johan Ekstrom,male,45,0,0,347061,6.9750,S
130,131,0,3,Mr. Jozef Drazenoic,male,33,0,0,349241,7.8958,C
131,132,0,3,Mr. Domingos Fernandeo Coelho,male,20,0,0,SOTONOQ3101307,7.0500,S
132,133,0,3,Mrs. Alexander A (Grace Charity Laury) Robins,female,47,1,0,A53337,14.5000,S
133,134,1,2,Mrs. Leopold (Mathilde Francoise Pede) Weisz,female,29,1,0,228414,26.0000,S
134,135,0,2,Mr. Samuel James Hayden Sobey,male,25,0,0,CA29178,13.0000,S
135,136,0,2,Mr. Emile Richard,male,23,0,0,SCPARIS2133,15.0458,C
136,137,1,1,Miss. Helen Monypeny Newsom,female,19,0,2,11752,26.2833,S
137,138,0,1,Mr. Jacques Heath Futrelle,male,37,1,0,113803,53.1000,S
138,139,0,3,Mr. Olaf Elon Osen,male,16,0,0,7534,9.2167,S
139,140,0,1,Mr. Victor Giglio,male,24,0,0,PC17593,79.2000,C
141,142,1,3,Miss. Anna Sofia Nysten,female,22,0,0,347081,7.7500,S
142,143,1,3,Mrs. Pekka Pietari (Elin Matilda Dolck) Hakka...,female,24,1,0,STONO23101279,15.8500,S
143,144,0,3,Mr. Jeremiah Burke,male,19,0,0,365222,6.7500,Q
144,145,0,2,Mr. Edgardo Samuel Andrew,male,18,0,0,231945,11.5000,S
145,146,0,2,Mr. Joseph Charles Nicholls,male,19,1,1,CA33112,36.7500,S
146,147,1,3,"Mr. August Edvard (""Wennerstrom"") Andersson",male,27,0,0,350043,7.7958,S
147,148,0,3,"Miss. Robina Maggie ""Ruby"" Ford",female,9,2,2,WC6608,34.3750,S
148,149,0,2,"Mr. Michel (""Louis M Hoffman"") Navratil",male,36,0,2,230080,26.0000,S
149,150,0,2,Rev. Thomas Roussel Davids Byles,male,42,0,0,244310,13.0000,S
150,151,0,2,Rev. Robert James Bateman,male,51,0,0,SOP1166,12.5250,S
151,152,1,1,Mrs. Thomas (Edith Wearne) Pears,female,22,1,0,113776,66.6000,S
152,153,0,3,Mr. Alfonzo Meo,male,55,0,0,A511206,8.0500,S
153,154,0,3,Mr. Austin Blyler van Billiard,male,40,0,2,A5851,14.5000,S
155,156,0,1,Mr. Charles Duane Williams,male,51,0,1,PC17597,61.3792,C
156,157,1,3,"Miss. Katherine ""Katie"" Gilnagh",female,16,0,0,35851,7.7333,Q
157,158,0,3,Mr. Harry Corn,male,30,0,0,SOTONOQ392090,8.0500,S
160,161,0,3,Mr. John Hatfield Cribb,male,44,0,1,371362,16.1000,S
161,162,1,2,"Mrs. James (Elizabeth ""Bessie"" Inglis Milne) ...",female,40,0,0,CA33595,15.7500,S
162,163,0,3,Mr. John Viktor Bengtsson,male,26,0,0,347068,7.7750,S
163,164,0,3,Mr. Jovo Calic,male,17,0,0,315093,8.6625,S
164,165,0,3,Master. Eino Viljami Panula,male,1,4,1,3101295,39.6875,S
165,166,1,3,"Master. Frank John William ""Frankie"" Goldsmith",male,9,0,2,363291,20.5250,S
167,168,0,3,Mrs. William (Anna Bernhardina Karlsson) Skoog,female,45,1,4,347088,27.9000,S
169,170,0,3,Mr. Lee Ling,male,28,0,0,1601,56.4958,S
170,171,0,1,Mr. Wyckoff Van der hoef,male,61,0,0,111240,33.5000,S
171,172,0,3,Master. Arthur Rice,male,4,4,1,382652,29.1250,Q
172,173,1,3,Miss. Eleanor Ileen Johnson,female,1,1,1,347742,11.1333,S
173,174,0,3,Mr. Antti Wilhelm Sivola,male,21,0,0,STONO23101280,7.9250,S
174,175,0,1,Mr. James Clinch Smith,male,56,0,0,17764,30.6958,C
175,176,0,3,Mr. Klas Albin Klasen,male,18,1,1,350404,7.8542,S
177,178,0,1,Miss. Ann Elizabeth Isham,female,50,0,0,PC17595,28.7125,C
178,179,0,2,Mr. Reginald Hale,male,30,0,0,250653,13.0000,S
179,180,0,3,Mr. Lionel Leonard,male,36,0,0,LINE,0.0000,S
182,183,0,3,Master. Clarence Gustaf Hugo Asplund,male,9,4,2,347077,31.3875,S
183,184,1,2,Master. Richard F Becker,male,1,2,1,230136,39.0000,S
184,185,1,3,Miss. Luise Gretchen Kink-Heilmann,female,4,0,2,315153,22.0250,S
187,188,1,1,"Mr. Charles Hallace (""Mr C Rolmane"") Romaine",male,45,0,0,111428,26.5500,S
188,189,0,3,Mr. John Bourke,male,40,1,1,364849,15.5000,Q
189,190,0,3,Mr. Stjepan Turcin,male,36,0,0,349247,7.8958,S
190,191,1,2,Mrs. (Rosa) Pinsky,female,32,0,0,234604,13.0000,S
191,192,0,2,Mr. William Carbines,male,19,0,0,28424,13.0000,S
192,193,1,3,Miss. Carla Christine Nielsine Andersen-Jensen,female,19,1,0,350046,7.8542,S
193,194,1,2,Master. Michel M Navratil,male,3,1,1,230080,26.0000,S
194,195,1,1,Mrs. James Joseph (Margaret Tobin) Brown,female,44,0,0,PC17610,27.7208,C
195,196,1,1,Miss. Elise Lurette,female,58,0,0,PC17569,146.5208,C
197,198,0,3,Mr. Karl Siegwart Andreas Olsen,male,42,0,1,4579,8.4042,S
199,200,0,2,"Miss. Henriette (""Mrs Harbeck"") Yrois",female,24,0,0,248747,13.0000,S
200,201,0,3,Mr. Nestor Cyriel Vande Walle,male,28,0,0,345770,9.5000,S
202,203,0,3,Mr. Jakob Alfred Johanson,male,34,0,0,3101264,6.4958,S
203,204,0,3,Mr. Gerious Youseff,male,45,0,0,2628,7.2250,C
204,205,1,3,"Mr. Gurshon ""Gus"" Cohen",male,18,0,0,A53540,8.0500,S
205,206,0,3,Miss. Telma Matilda Strom,female,2,0,1,347054,10.4625,S
206,207,0,3,Mr. Karl Alfred Backstrom,male,32,1,0,3101278,15.8500,S
207,208,1,3,Mr. Nassef Cassem Albimona,male,26,0,0,2699,18.7875,C
208,209,1,3,"Miss. Helen ""Ellen"" Carr",female,16,0,0,367231,7.7500,Q
209,210,1,1,Mr. Henry Blank,male,40,0,0,112277,31.0000,C
210,211,0,3,Mr. Ahmed Ali,male,24,0,0,SOTONOQ3101311,7.0500,S
211,212,1,2,Miss. Clear Annie Cameron,female,35,0,0,FCC13528,21.0000,S
212,213,0,3,Mr. John Henry Perkin,male,22,0,0,A521174,7.2500,S
213,214,0,2,Mr. Hans Kristensen Givard,male,30,0,0,250646,13.0000,S
215,216,1,1,Miss. Madeleine Newell,female,31,1,0,35273,113.2750,C
216,217,1,3,Miss. Eliina Honkanen,female,27,0,0,STONO23101283,7.9250,S
217,218,0,2,Mr. Sidney Samuel Jacobsohn,male,42,1,0,243847,27.0000,S
218,219,1,1,Miss. Albina Bazzani,female,32,0,0,11813,76.2917,C
219,220,0,2,Mr. Walter Harris,male,30,0,0,WC14208,10.5000,S
220,221,1,3,Mr. Victor Francis Sunderland,male,16,0,0,SOTONOQ392089,8.0500,S
221,222,0,2,Mr. James H Bracken,male,27,0,0,220367,13.0000,S
222,223,0,3,Mr. George Henry Green,male,51,0,0,21440,8.0500,S
224,225,1,1,Mr. Frederick Maxfield Hoyt,male,38,1,0,19943,90.0000,S
225,226,0,3,Mr. Karl Ivar Sven Berglund,male,22,0,0,PP4348,9.3500,S
226,227,1,2,Mr. William John Mellors,male,19,0,0,SWPP751,10.5000,S
227,228,0,3,"Mr. John Hall (""Henry"") Lovell",male,20,0,0,A521173,7.2500,S
228,229,0,2,Mr. Arne Jonas Fahlstrom,male,18,0,0,236171,13.0000,S
230,231,1,1,Mrs. Henry Birkhardt (Irene Wallach) Harris,female,35,1,0,36973,83.4750,S
231,232,0,3,Mr. Bengt Edvin Larsson,male,29,0,0,347067,7.7750,S
232,233,0,2,Mr. Ernst Adolf Sjostedt,male,59,0,0,237442,13.5000,S
233,234,1,3,Miss. Lillian Gertrud Asplund,female,5,4,2,347077,31.3875,S
234,235,0,2,Mr. Robert William Norman Leyson,male,24,0,0,CA29566,10.5000,S
236,237,0,2,Mr. Stephen Hold,male,44,1,0,26707,26.0000,S
237,238,1,2,"Miss. Marjorie ""Lottie"" Collyer",female,8,0,2,CA31921,26.2500,S
238,239,0,2,Mr. Frederick William Pengelly,male,19,0,0,28665,10.5000,S
239,240,0,2,Mr. George Henry Hunt,male,33,0,0,SCOW1585,12.2750,S
242,243,0,2,Mr. Reginald Charles Coleridge,male,29,0,0,WC14263,10.5000,S
243,244,0,3,Mr. Matti Alexanteri Maenpaa,male,22,0,0,STONO23101275,7.1250,S
244,245,0,3,Mr. Sleiman Attalah,male,30,0,0,2694,7.2250,C
245,246,0,1,Dr. William Edward Minahan,male,44,2,0,19928,90.0000,Q
246,247,0,3,Miss. Agda Thorilda Viktoria Lindahl,female,25,0,0,347071,7.7750,S
247,248,1,2,Mrs. William (Anna) Hamalainen,female,24,0,2,250649,14.5000,S
248,249,1,1,Mr. Richard Leonard Beckwith,male,37,1,1,11751,52.5542,S
249,250,0,2,Rev. Ernest Courtenay Carter,male,54,1,0,244252,26.0000,S
251,252,0,3,Mrs. Wilhelm (Elna Matilda Persson) Strom,female,29,1,1,347054,10.4625,S
252,253,0,1,Mr. William Thomas Stead,male,62,0,0,113514,26.5500,S
253,254,0,3,Mr. William Arthur Lobb,male,30,1,0,A53336,16.1000,S
254,255,0,3,Mrs. Viktor (Helena Wilhelmina) Rosblom,female,41,0,2,370129,20.2125,S
255,256,1,3,Mrs. Darwis (Hanne Youssef Razi) Touma,female,29,0,2,2650,15.2458,C
257,258,1,1,Miss. Gladys Cherry,female,30,0,0,110152,86.5000,S
258,259,1,1,Miss. Anna Ward,female,35,0,0,PC17755,512.3292,C
259,260,1,2,Mrs. (Lutie Davis) Parrish,female,50,0,1,230433,26.0000,S
261,262,1,3,Master. Edvin Rojj Felix Asplund,male,3,4,2,347077,31.3875,S
262,263,0,1,Mr. Emil Taussig,male,52,1,1,110413,79.6500,S
263,264,0,1,Mr. William Harrison,male,40,0,0,112059,0.0000,S
265,266,0,2,Mr. David Reeves,male,36,0,0,CA17248,10.5000,S
266,267,0,3,Mr. Ernesti Arvid Panula,male,16,4,1,3101295,39.6875,S
267,268,1,3,Mr. Ernst Ulrik Persson,male,25,1,0,347083,7.7750,S
268,269,1,1,Mrs. William Thompson (Edith Junkins) Graham,female,58,0,1,PC17582,153.4625,S
269,270,1,1,Miss. Amelia Bissette,female,35,0,0,PC17760,135.6333,S
271,272,1,3,Mr. William Henry Tornquist,male,25,0,0,LINE,0.0000,S
272,273,1,2,Mrs. (Elizabeth Anne Maidment) Mellinger,female,41,0,1,250644,19.5000,S
273,274,0,1,Mr. Charles H Natsch,male,37,0,1,PC17596,29.7000,C
275,276,1,1,Miss. Kornelia Theodosia Andrews,female,63,1,0,13502,77.9583,S
276,277,0,3,Miss. Augusta Charlotta Lindblom,female,45,0,0,347073,7.7500,S
278,279,0,3,Master. Eric Rice,male,7,4,1,382652,29.1250,Q
279,280,1,3,Mrs. Stanton (Rosa Hunt) Abbott,female,35,1,1,CA2673,20.2500,S
280,281,0,3,Mr. Frank Duane,male,65,0,0,336439,7.7500,Q
281,282,0,3,Mr. Nils Johan Goransson Olsson,male,28,0,0,347464,7.8542,S
282,283,0,3,Mr. Alfons de Pelsmaeker,male,16,0,0,345778,9.5000,S
283,284,1,3,Mr. Edward Arthur Dorking,male,19,0,0,A510482,8.0500,S
285,286,0,3,Mr. Ivan Stankovic,male,33,0,0,349239,8.6625,C
286,287,1,3,Mr. Theodore de Mulder,male,30,0,0,345774,9.5000,S
287,288,0,3,Mr. Penko Naidenoff,male,22,0,0,349206,7.8958,S
288,289,1,2,Mr. Masabumi Hosono,male,42,0,0,237798,13.0000,S
289,290,1,3,Miss. Kate Connolly,female,22,0,0,370373,7.7500,Q
290,291,1,1,"Miss. Ellen ""Nellie"" Barber",female,26,0,0,19877,78.8500,S
291,292,1,1,Mrs. Dickinson H (Helen Walton) Bishop,female,19,1,0,11967,91.0792,C
292,293,0,2,Mr. Rene Jacques Levy,male,36,0,0,SCParis2163,12.8750,C
293,294,0,3,Miss. Aloisia Haas,female,24,0,0,349236,8.8500,S
294,295,0,3,Mr. Ivan Mineff,male,24,0,0,349233,7.8958,S
296,297,0,3,Mr. Mansour Hanna,male,23,0,0,2693,7.2292,C
297,298,0,1,Miss. Helen Loraine Allison,female,2,1,2,113781,151.5500,S
299,300,1,1,Mrs. James (Helene DeLaudeniere Chaput) Baxter,female,50,0,1,PC17558,247.5208,C
302,303,0,3,Mr. William Cahoone Jr Johnson,male,19,0,0,LINE,0.0000,S
307,308,1,1,Mrs. Victor de Satode (Maria Josefa Perez de ...,female,17,1,0,PC17758,108.9000,C
308,309,0,2,Mr. Samuel Abelson,male,30,1,0,PPP3381,24.0000,C
309,310,1,1,Miss. Laura Mabel Francatelli,female,30,0,0,PC17485,56.9292,C
310,311,1,1,Miss. Margaret Bechstein Hays,female,24,0,0,11767,83.1583,C
311,312,1,1,Miss. Emily Borie Ryerson,female,18,2,2,PC17608,262.3750,C
312,313,0,2,Mrs. William (Anna Sylfven) Lahtinen,female,26,1,1,250651,26.0000,S
313,314,0,3,Mr. Ignjac Hendekovic,male,28,0,0,349243,7.8958,S
314,315,0,2,Mr. Benjamin Hart,male,43,1,1,FCC13529,26.2500,S
315,316,1,3,Miss. Helmina Josefina Nilsson,female,26,0,0,347470,7.8542,S
316,317,1,2,Mrs. Sinai (Miriam Sternin) Kantor,female,24,1,0,244367,26.0000,S
317,318,0,2,Dr. Ernest Moraweck,male,54,0,0,29011,14.0000,S
318,319,1,1,Miss. Mary Natalie Wick,female,31,0,2,36928,164.8667,S
319,320,1,1,Mrs. Frederic Oakley (Margaretta Corning Ston...,female,40,1,1,16966,134.5000,C
320,321,0,3,Mr. Samuel Dennis,male,22,0,0,A521172,7.2500,S
321,322,0,3,Mr. Yoto Danoff,male,27,0,0,349219,7.8958,S
322,323,1,2,Miss. Hilda Mary Slayter,female,30,0,0,234818,12.3500,Q
323,324,1,2,Mrs. Albert Francis (Sylvia Mae Harbaugh) Cal...,female,22,1,1,248738,29.0000,S
325,326,1,1,Miss. Marie Grice Young,female,36,0,0,PC17760,135.6333,C
326,327,0,3,Mr. Johan Hansen Nysveen,male,61,0,0,345364,6.2375,S
327,328,1,2,Mrs. (Ada E Hall) Ball,female,36,0,0,28551,13.0000,S
328,329,1,3,Mrs. Frank John (Emily Alice Brown) Goldsmith,female,31,1,1,363291,20.5250,S
329,330,1,1,Miss. Jean Gertrude Hippach,female,16,0,1,111361,57.9792,C
331,332,0,1,Mr. Austen Partner,male,45,0,0,113043,28.5000,S
332,333,0,1,Mr. George Edward Graham,male,38,0,1,PC17582,153.4625,S
333,334,0,3,Mr. Leo Edmondus Vander Planke,male,16,2,0,345764,18.0000,S
336,337,0,1,Mr. Thomas Clinton Pears,male,29,1,0,113776,66.6000,S
337,338,1,1,Miss. Elizabeth Margaret Burns,female,41,0,0,16966,134.5000,C
338,339,1,3,Mr. Karl Edwart Dahl,male,45,0,0,7598,8.0500,S
339,340,0,1,Mr. Stephen Weart Blackwell,male,45,0,0,113784,35.5000,S
340,341,1,2,Master. Edmond Roger Navratil,male,2,1,1,230080,26.0000,S
341,342,1,1,Miss. Alice Elizabeth Fortune,female,24,3,2,19950,263.0000,S
342,343,0,2,Mr. Erik Gustaf Collander,male,28,0,0,248740,13.0000,S
343,344,0,2,Mr. Charles Frederick Waddington Sedgwick,male,25,0,0,244361,13.0000,S
344,345,0,2,Mr. Stanley Hubert Fox,male,36,0,0,229236,13.0000,S
345,346,1,2,"Miss. Amelia ""Mildred"" Brown",female,24,0,0,248733,13.0000,S
346,347,1,2,Miss. Marion Elsie Smith,female,40,0,0,31418,13.0000,S
348,349,1,3,"Master. William Loch ""William"" Coutts",male,3,1,1,CA37671,15.9000,S
349,350,0,3,Mr. Jovan Dimic,male,42,0,0,315088,8.6625,S
350,351,0,3,Mr. Nils Martin Odahl,male,23,0,0,7267,9.2250,S
352,353,0,3,Mr. Tannous Elias,male,15,1,1,2695,7.2292,C
353,354,0,3,Mr. Josef Arnold-Franchi,male,25,1,0,349237,17.8000,S
355,356,0,3,Mr. Leo Peter Vanden Steen,male,28,0,0,345783,9.5000,S
356,357,1,1,Miss. Elsie Edith Bowerman,female,22,0,1,113505,55.0000,S
357,358,0,2,Miss. Annie Clemmer Funk,female,38,0,0,237671,13.0000,S
360,361,0,3,Mr. Wilhelm Skoog,male,40,1,4,347088,27.9000,S
361,362,0,2,Mr. Sebastiano del Carlo,male,29,1,0,SCPARIS2167,27.7208,C
362,363,0,3,Mrs. (Catherine David) Barbara,female,45,0,1,2691,14.4542,C
363,364,0,3,Mr. Adola Asim,male,35,0,0,SOTONOQ3101310,7.0500,S

In [33]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 705 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  705 non-null    int64
 1   Survived     705 non-null    int64
 2   Pclass       705 non-null    int64
 3   Full_name    705 non-null    object
 4   Sex          705 non-null    object
 5   Age          705 non-null    int64
 6   SibSp        705 non-null    int64
 7   Parch        705 non-null    int64
 8   Ticket       705 non-null    object
 9   Fare         705 non-null    float64
 10  Embarked     705 non-null    object
dtypes: float64(1), int64(6), object(4)
memory usage: 66.1+ KB

In [9]:
df1['Ticket']=df1['Ticket'].str.replace(r'[^a-zA-Z0-9]','',regex= True)

In [10]:
df1[['first_name','last_name']]=df1['Name'].str.split(',',n=2,expand=True)

In [11]:
df1['Full_name']=df1['last_name'] + ' '+(df1['first_name'])

In [12]:
df1=df1.drop(columns=['Name','first_name','last_name'])

In [13]:
cols=list(df1.columns)
cols.insert(3,cols.pop(cols.index('Full_name')))
df1=df1[cols]

In [14]:
df1=df1.drop(columns='Cabin')

In [16]:
df1['Age']=df1['Age'].fillna(0).astype(int)
df1

,PassengerId,Survived,Pclass,Full_name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,Mr. Owen Harris Braund,male,22,1,0,A521171,7.2500,S
1,2,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cu...,female,38,1,0,PC17599,71.2833,C
2,3,1,3,Miss. Laina Heikkinen,female,26,0,0,STONO23101282,7.9250,S
3,4,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35,1,0,113803,53.1000,S
4,5,0,3,Mr. William Henry Allen,male,35,0,0,373450,8.0500,S
5,6,0,3,Mr. James Moran,male,0,0,0,330877,8.4583,Q
6,7,0,1,Mr. Timothy J McCarthy,male,54,0,0,17463,51.8625,S
7,8,0,3,Master. Gosta Leonard Palsson,male,2,3,1,349909,21.0750,S
8,9,1,3,Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson,female,27,0,2,347742,11.1333,S
9,10,1,2,Mrs. Nicholas (Adele Achem) Nasser,female,14,1,0,237736,30.0708,C
10,11,1,3,Miss. Marguerite Rut Sandstrom,female,4,1,1,PP9549,16.7000,S
11,12,1,1,Miss. Elizabeth Bonnell,female,58,0,0,113783,26.5500,S
12,13,0,3,Mr. William Henry Saundercock,male,20,0,0,A52151,8.0500,S
13,14,0,3,Mr. Anders Johan Andersson,male,39,1,5,347082,31.2750,S
14,15,0,3,Miss. Hulda Amanda Adolfina Vestrom,female,14,0,0,350406,7.8542,S
15,16,1,2,Mrs. (Mary D Kingcome) Hewlett,female,55,0,0,248706,16.0000,S
16,17,0,3,Master. Eugene Rice,male,2,4,1,382652,29.1250,Q
17,18,1,2,Mr. Charles Eugene Williams,male,0,0,0,244373,13.0000,S
18,19,0,3,Mrs. Julius (Emelia Maria Vandemoortele) Vand...,female,31,1,0,345763,18.0000,S
19,20,1,3,Mrs. Fatima Masselmani,female,0,0,0,2649,7.2250,C
20,21,0,2,Mr. Joseph J Fynney,male,35,0,0,239865,26.0000,S
21,22,1,2,Mr. Lawrence Beesley,male,34,0,0,248698,13.0000,S
22,23,1,3,"Miss. Anna ""Annie"" McGowan",female,15,0,0,330923,8.0292,Q
23,24,1,1,Mr. William Thompson Sloper,male,28,0,0,113788,35.5000,S
24,25,0,3,Miss. Torborg Danira Palsson,female,8,3,1,349909,21.0750,S
25,26,1,3,Mrs. Carl Oscar (Selma Augusta Emilia Johanss...,female,38,1,5,347077,31.3875,S
26,27,0,3,Mr. Farred Chehab Emir,male,0,0,0,2631,7.2250,C
27,28,0,1,Mr. Charles Alexander Fortune,male,19,3,2,19950,263.0000,S
28,29,1,3,"Miss. Ellen ""Nellie"" O'Dwyer",female,0,0,0,330959,7.8792,Q
29,30,0,3,Mr. Lalio Todoroff,male,0,0,0,349216,7.8958,S
30,31,0,1,Don. Manuel E Uruchurtu,male,40,0,0,PC17601,27.7208,C
31,32,1,1,Mrs. William Augustus (Marie Eugenie) Spencer,female,0,1,0,PC17569,146.5208,C
32,33,1,3,Miss. Mary Agatha Glynn,female,0,0,0,335677,7.7500,Q
33,34,0,2,Mr. Edward H Wheadon,male,66,0,0,CA24579,10.5000,S
34,35,0,1,Mr. Edgar Joseph Meyer,male,28,1,0,PC17604,82.1708,C
35,36,0,1,Mr. Alexander Oskar Holverson,male,42,1,0,113789,52.0000,S
36,37,1,3,Mr. Hanna Mamee,male,0,0,0,2677,7.2292,C
37,38,0,3,Mr. Ernest Charles Cann,male,21,0,0,A52152,8.0500,S
38,39,0,3,Miss. Augusta Maria Vander Planke,female,18,2,0,345764,18.0000,S
39,40,1,3,Miss. Jamila Nicola-Yarred,female,14,1,0,2651,11.2417,C
40,41,0,3,Mrs. Johan (Johanna Persdotter Larsson) Ahlin,female,40,1,0,7546,9.4750,S
41,42,0,2,Mrs. William John Robert (Dorothy Ann Wonnaco...,female,27,1,0,11668,21.0000,S
42,43,0,3,Mr. Theodor Kraeff,male,0,0,0,349253,7.8958,C
43,44,1,2,Miss. Simonne Marie Anne Andree Laroche,female,3,1,2,SCParis2123,41.5792,C
44,45,1,3,Miss. Margaret Delia Devaney,female,19,0,0,330958,7.8792,Q
45,46,0,3,Mr. William John Rogers,male,0,0,0,SCA423567,8.0500,S
46,47,0,3,Mr. Denis Lennon,male,0,1,0,370371,15.5000,Q
47,48,1,3,Miss. Bridget O'Driscoll,female,0,0,0,14311,7.7500,Q
48,49,0,3,Mr. Youssef Samaan,male,0,2,0,2662,21.6792,C
49,50,0,3,Mrs. Josef (Josefine Franchi) Arnold-Franchi,female,18,1,0,349237,17.8000,S
50,51,0,3,Master. Juha Niilo Panula,male,7,4,1,3101295,39.6875,S
51,52,0,3,Mr. Richard Cater Nosworthy,male,21,0,0,A439886,7.8000,S
52,53,1,1,Mrs. Henry Sleeper (Myna Haxtun) Harper,female,49,1,0,PC17572,76.7292,C
53,54,1,2,Mrs. Lizzie (Elizabeth Anne Wilkinson) Faunth...,female,29,1,0,2926,26.0000,S
54,55,0,1,Mr. Engelhart Cornelius Ostby,male,65,0,1,113509,61.9792,C
55,56,1,1,Mr. Hugh Woolner,male,0,0,0,19947,35.5000,S
56,57,1,2,Miss. Emily Rugg,female,21,0,0,CA31026,10.5000,S
57,58,0,3,Mr. Mansouer Novel,male,28,0,0,2697,7.2292,C
58,59,1,2,Miss. Constance Mirium West,female,5,1,2,CA34651,27.7500,S
59,60,0,3,Master. William Frederick Goodwin,male,11,5,2,CA2144,46.9000,S
60,61,0,3,Mr. Orsen Sirayanian,male,22,0,0,2669,7.2292,C
61,62,1,1,Miss. Amelie Icard,female,38,0,0,113572,80.0000,NaN
62,63,0,1,Mr. Henry Birkhardt Harris,male,45,1,0,36973,83.4750,S
63,64,0,3,Master. Harald Skoog,male,4,3,2,347088,27.9000,S
64,65,0,1,Mr. Albert A Stewart,male,0,0,0,PC17605,27.7208,C
65,66,1,3,Master. Gerios Moubarek,male,0,1,1,2661,15.2458,C
66,67,1,2,Mrs. (Elizabeth Ramell) Nye,female,29,0,0,CA29395,10.5000,S
67,68,0,3,Mr. Ernest James Crease,male,19,0,0,SP3464,8.1583,S
68,69,1,3,Miss. Erna Alexandra Andersson,female,17,4,2,3101281,7.9250,S
69,70,0,3,Mr. Vincenz Kink,male,26,2,0,315151,8.6625,S
70,71,0,2,Mr. Stephen Curnow Jenkin,male,32,0,0,CA33111,10.5000,S
71,72,0,3,Miss. Lillian Amy Goodwin,female,16,5,2,CA2144,46.9000,S
72,73,0,2,Mr. Ambrose Jr Hood,male,21,0,0,SOC14879,73.5000,S
73,74,0,3,Mr. Apostolos Chronopoulos,male,26,1,0,2680,14.4542,C
74,75,1,3,Mr. Lee Bing,male,32,0,0,1601,56.4958,S
75,76,0,3,Mr. Sigurd Hansen Moen,male,25,0,0,348123,7.6500,S
76,77,0,3,Mr. Ivan Staneff,male,0,0,0,349208,7.8958,S
77,78,0,3,Mr. Rahamin Haim Moutal,male,0,0,0,374746,8.0500,S
78,79,1,2,Master. Alden Gates Caldwell,male,0,0,2,248738,29.0000,S
79,80,1,3,Miss. Elizabeth Dowdell,female,30,0,0,364516,12.4750,S
80,81,0,3,Mr. Achille Waelens,male,22,0,0,345767,9.0000,S
81,82,1,3,Mr. Jan Baptist Sheerlinck,male,29,0,0,345779,9.5000,S
82,83,1,3,Miss. Brigdet Delia McDermott,female,0,0,0,330932,7.7875,Q
83,84,0,1,Mr. Francisco M Carrau,male,28,0,0,113059,47.1000,S
84,85,1,2,Miss. Bertha Ilett,female,17,0,0,SOC14885,10.5000,S
85,86,1,3,Mrs. Karl Alfred (Maria Mathilda Gustafsson) ...,female,33,3,0,3101278,15.8500,S
86,87,0,3,Mr. William Neal Ford,male,16,1,3,WC6608,34.3750,S
87,88,0,3,Mr. Selman Francis Slocovski,male,0,0,0,SOTONOQ392086,8.0500,S
88,89,1,1,Miss. Mabel Helen Fortune,female,23,3,2,19950,263.0000,S
89,90,0,3,Mr. Francesco Celotti,male,24,0,0,343275,8.0500,S
90,91,0,3,Mr. Emil Christmann,male,29,0,0,343276,8.0500,S
91,92,0,3,Mr. Paul Edvin Andreasson,male,20,0,0,347466,7.8542,S
92,93,0,1,Mr. Herbert Fuller Chaffee,male,46,1,0,WEP5734,61.1750,S
93,94,0,3,Mr. Bertram Frank Dean,male,26,1,2,CA2315,20.5750,S
94,95,0,3,Mr. Daniel Coxon,male,59,0,0,364500,7.2500,S
95,96,0,3,Mr. Charles Joseph Shorney,male,0,0,0,374910,8.0500,S
96,97,0,1,Mr. George B Goldschmidt,male,71,0,0,PC17754,34.6542,C
97,98,1,1,Mr. William Bertram Greenfield,male,23,0,1,PC17759,63.3583,C
98,99,1,2,Mrs. John T (Ada Julia Bone) Doling,female,34,0,1,231919,23.0000,S
99,100,0,2,Mr. Sinai Kantor,male,34,1,0,244367,26.0000,S
100,101,0,3,Miss. Matilda Petranec,female,28,0,0,349245,7.8958,S
101,102,0,3,"Mr. Pastcho (""Pentcho"") Petroff",male,0,0,0,349215,7.8958,S
102,103,0,1,Mr. Richard Frasar White,male,21,0,1,35281,77.2875,S
103,104,0,3,Mr. Gustaf Joel Johansson,male,33,0,0,7540,8.6542,S
104,105,0,3,Mr. Anders Vilhelm Gustafsson,male,37,2,0,3101276,7.9250,S
105,106,0,3,Mr. Stoytcho Mionoff,male,28,0,0,349207,7.8958,S
106,107,1,3,Miss. Anna Kristine Salkjelsvik,female,21,0,0,343120,7.6500,S
107,108,1,3,Mr. Albert Johan Moss,male,0,0,0,312991,7.7750,S
108,109,0,3,Mr. Tido Rekic,male,38,0,0,349249,7.8958,S
109,110,1,3,Miss. Bertha Moran,female,0,1,0,371110,24.1500,Q
110,111,0,1,Mr. Walter Chamberlain Porter,male,47,0,0,110465,52.0000,S
111,112,0,3,Miss. Hileni Zabour,female,14,1,0,2665,14.4542,C
112,113,0,3,Mr. David John Barton,male,22,0,0,324669,8.0500,S
113,114,0,3,Miss. Katriina Jussila,female,20,1,0,4136,9.8250,S
114,115,0,3,Miss. Malake Attalah,female,17,0,0,2627,14.4583,C
115,116,0,3,Mr. Edvard Pekoniemi,male,21,0,0,STONO23101294,7.9250,S
116,117,0,3,Mr. Patrick Connors,male,70,0,0,370369,7.7500,Q
117,118,0,2,Mr. William John Robert Turpin,male,29,1,0,11668,21.0000,S
118,119,0,1,Mr. Quigg Edmond Baxter,male,24,0,1,PC17558,247.5208,C
119,120,0,3,Miss. Ellis Anna Maria Andersson,female,2,4,2,347082,31.2750,S
120,121,0,2,Mr. Stanley George Hickman,male,21,2,0,SOC14879,73.5000,S
121,122,0,3,Mr. Leonard Charles Moore,male,0,0,0,A454510,8.0500,S
122,123,0,2,Mr. Nicholas Nasser,male,32,1,0,237736,30.0708,C
123,124,1,2,Miss. Susan Webber,female,32,0,0,27267,13.0000,S
124,125,0,1,Mr. Percival Wayland White,male,54,0,1,35281,77.2875,S
125,126,1,3,Master. Elias Nicola-Yarred,male,12,1,0,2651,11.2417,C
126,127,0,3,Mr. Martin McMahon,male,0,0,0,370372,7.7500,Q
127,128,1,3,Mr. Fridtjof Arne Madsen,male,24,0,0,C17369,7.1417,S
128,129,1,3,Miss. Anna Peter,female,0,1,1,2668,22.3583,C
129,130,0,3,Mr. Johan Ekstrom,male,45,0,0,347061,6.9750,S
130,131,0,3,Mr. Jozef Drazenoic,male,33,0,0,349241,7.8958,C
131,132,0,3,Mr. Domingos Fernandeo Coelho,male,20,0,0,SOTONOQ3101307,7.0500,S
132,133,0,3,Mrs. Alexander A (Grace Charity Laury) Robins,female,47,1,0,A53337,14.5000,S
133,134,1,2,Mrs. Leopold (Mathilde Francoise Pede) Weisz,female,29,1,0,228414,26.0000,S
134,135,0,2,Mr. Samuel James Hayden Sobey,male,25,0,0,CA29178,13.0000,S
135,136,0,2,Mr. Emile Richard,male,23,0,0,SCPARIS2133,15.0458,C
136,137,1,1,Miss. Helen Monypeny Newsom,female,19,0,2,11752,26.2833,S
137,138,0,1,Mr. Jacques Heath Futrelle,male,37,1,0,113803,53.1000,S
138,139,0,3,Mr. Olaf Elon Osen,male,16,0,0,7534,9.2167,S
139,140,0,1,Mr. Victor Giglio,male,24,0,0,PC17593,79.2000,C
140,141,0,3,Mrs. Joseph (Sultana) Boulos,female,0,0,2,2678,15.2458,C
141,142,1,3,Miss. Anna Sofia Nysten,female,22,0,0,347081,7.7500,S
142,143,1,3,Mrs. Pekka Pietari (Elin Matilda Dolck) Hakka...,female,24,1,0,STONO23101279,15.8500,S
143,144,0,3,Mr. Jeremiah Burke,male,19,0,0,365222,6.7500,Q
144,145,0,2,Mr. Edgardo Samuel Andrew,male,18,0,0,231945,11.5000,S
145,146,0,2,Mr. Joseph Charles Nicholls,male,19,1,1,CA33112,36.7500,S
146,147,1,3,"Mr. August Edvard (""Wennerstrom"") Andersson",male,27,0,0,350043,7.7958,S
147,148,0,3,"Miss. Robina Maggie ""Ruby"" Ford",female,9,2,2,WC6608,34.3750,S
148,149,0,2,"Mr. Michel (""Louis M Hoffman"") Navratil",male,36,0,2,230080,26.0000,S
149,150,0,2,Rev. Thomas Roussel Davids Byles,male,42,0,0,244310,13.0000,S
150,151,0,2,Rev. Robert James Bateman,male,51,0,0,SOP1166,12.5250,S
151,152,1,1,Mrs. Thomas (Edith Wearne) Pears,female,22,1,0,113776,66.6000,S
152,153,0,3,Mr. Alfonzo Meo,male,55,0,0,A511206,8.0500,S
153,154,0,3,Mr. Austin Blyler van Billiard,male,40,0,2,A5851,14.5000,S
154,155,0,3,Mr. Ole Martin Olsen,male,0,0,0,Fa265302,7.3125,S
155,156,0,1,Mr. Charles Duane Williams,male,51,0,1,PC17597,61.3792,C
156,157,1,3,"Miss. Katherine ""Katie"" Gilnagh",female,16,0,0,35851,7.7333,Q
157,158,0,3,Mr. Harry Corn,male,30,0,0,SOTONOQ392090,8.0500,S
158,159,0,3,Mr. Mile Smiljanic,male,0,0,0,315037,8.6625,S
159,160,0,3,Master. Thomas Henry Sage,male,0,8,2,CA2343,69.5500,S
160,161,0,3,Mr. John Hatfield Cribb,male,44,0,1,371362,16.1000,S
161,162,1,2,"Mrs. James (Elizabeth ""Bessie"" Inglis Milne) ...",female,40,0,0,CA33595,15.7500,S
162,163,0,3,Mr. John Viktor Bengtsson,male,26,0,0,347068,7.7750,S
163,164,0,3,Mr. Jovo Calic,male,17,0,0,315093,8.6625,S
164,165,0,3,Master. Eino Viljami Panula,male,1,4,1,3101295,39.6875,S
165,166,1,3,"Master. Frank John William ""Frankie"" Goldsmith",male,9,0,2,363291,20.5250,S
166,167,1,1,Mrs. (Edith Martha Bowerman) Chibnall,female,0,0,1,113505,55.0000,S
167,168,0,3,Mrs. William (Anna Bernhardina Karlsson) Skoog,female,45,1,4,347088,27.9000,S
168,169,0,1,Mr. John D Baumann,male,0,0,0,PC17318,25.9250,S
169,170,0,3,Mr. Lee Ling,male,28,0,0,1601,56.4958,S
170,171,0,1,Mr. Wyckoff Van der hoef,male,61,0,0,111240,33.5000,S
171,172,0,3,Master. Arthur Rice,male,4,4,1,382652,29.1250,Q
172,173,1,3,Miss. Eleanor Ileen Johnson,female,1,1,1,347742,11.1333,S
173,174,0,3,Mr. Antti Wilhelm Sivola,male,21,0,0,STONO23101280,7.9250,S
174,175,0,1,Mr. James Clinch Smith,male,56,0,0,17764,30.6958,C
175,176,0,3,Mr. Klas Albin Klasen,male,18,1,1,350404,7.8542,S
176,177,0,3,Master. Henry Forbes Lefebre,male,0,3,1,4133,25.4667,S
177,178,0,1,Miss. Ann Elizabeth Isham,female,50,0,0,PC17595,28.7125,C
178,179,0,2,Mr. Reginald Hale,male,30,0,0,250653,13.0000,S
179,180,0,3,Mr. Lionel Leonard,male,36,0,0,LINE,0.0000,S
180,181,0,3,Miss. Constance Gladys Sage,female,0,8,2,CA2343,69.5500,S
181,182,0,2,Mr. Rene Pernot,male,0,0,0,SCPARIS2131,15.0500,C
182,183,0,3,Master. Clarence Gustaf Hugo Asplund,male,9,4,2,347077,31.3875,S
183,184,1,2,Master. Richard F Becker,male,1,2,1,230136,39.0000,S
184,185,1,3,Miss. Luise Gretchen Kink-Heilmann,female,4,0,2,315153,22.0250,S
185,186,0,1,Mr. Hugh Roscoe Rood,male,0,0,0,113767,50.0000,S
186,187,1,3,"Mrs. Thomas (Johanna ""Hannah"" Godfrey) O'Brien",female,0,1,0,370365,15.5000,Q
187,188,1,1,"Mr. Charles Hallace (""Mr C Rolmane"") Romaine",male,45,0,0,111428,26.5500,S
188,189,0,3,Mr. John Bourke,male,40,1,1,364849,15.5000,Q
189,190,0,3,Mr. Stjepan Turcin,male,36,0,0,349247,7.8958,S
190,191,1,2,Mrs. (Rosa) Pinsky,female,32,0,0,234604,13.0000,S
191,192,0,2,Mr. William Carbines,male,19,0,0,28424,13.0000,S
192,193,1,3,Miss. Carla Christine Nielsine Andersen-Jensen,female,19,1,0,350046,7.8542,S
193,194,1,2,Master. Michel M Navratil,male,3,1,1,230080,26.0000,S
194,195,1,1,Mrs. James Joseph (Margaret Tobin) Brown,female,44,0,0,PC17610,27.7208,C
195,196,1,1,Miss. Elise Lurette,female,58,0,0,PC17569,146.5208,C
196,197,0,3,Mr. Robert Mernagh,male,0,0,0,368703,7.7500,Q
197,198,0,3,Mr. Karl Siegwart Andreas Olsen,male,42,0,1,4579,8.4042,S
198,199,1,3,"Miss. Margaret ""Maggie"" Madigan",female,0,0,0,370370,7.7500,Q
199,200,0,2,"Miss. Henriette (""Mrs Harbeck"") Yrois",female,24,0,0,248747,13.0000,S
200,201,0,3,Mr. Nestor Cyriel Vande Walle,male,28,0,0,345770,9.5000,S
201,202,0,3,Mr. Frederick Sage,male,0,8,2,CA2343,69.5500,S
202,203,0,3,Mr. Jakob Alfred Johanson,male,34,0,0,3101264,6.4958,S
203,204,0,3,Mr. Gerious Youseff,male,45,0,0,2628,7.2250,C
204,205,1,3,"Mr. Gurshon ""Gus"" Cohen",male,18,0,0,A53540,8.0500,S
205,206,0,3,Miss. Telma Matilda Strom,female,2,0,1,347054,10.4625,S
206,207,0,3,Mr. Karl Alfred Backstrom,male,32,1,0,3101278,15.8500,S
207,208,1,3,Mr. Nassef Cassem Albimona,male,26,0,0,2699,18.7875,C
208,209,1,3,"Miss. Helen ""Ellen"" Carr",female,16,0,0,367231,7.7500,Q
209,210,1,1,Mr. Henry Blank,male,40,0,0,112277,31.0000,C
210,211,0,3,Mr. Ahmed Ali,male,24,0,0,SOTONOQ3101311,7.0500,S
211,212,1,2,Miss. Clear Annie Cameron,female,35,0,0,FCC13528,21.0000,S
212,213,0,3,Mr. John Henry Perkin,male,22,0,0,A521174,7.2500,S
213,214,0,2,Mr. Hans Kristensen Givard,male,30,0,0,250646,13.0000,S
214,215,0,3,Mr. Philip Kiernan,male,0,1,0,367229,7.7500,Q
215,216,1,1,Miss. Madeleine Newell,female,31,1,0,35273,113.2750,C
216,217,1,3,Miss. Eliina Honkanen,female,27,0,0,STONO23101283,7.9250,S
217,218,0,2,Mr. Sidney Samuel Jacobsohn,male,42,1,0,243847,27.0000,S
218,219,1,1,Miss. Albina Bazzani,female,32,0,0,11813,76.2917,C
219,220,0,2,Mr. Walter Harris,male,30,0,0,WC14208,10.5000,S
220,221,1,3,Mr. Victor Francis Sunderland,male,16,0,0,SOTONOQ392089,8.0500,S
221,222,0,2,Mr. James H Bracken,male,27,0,0,220367,13.0000,S
222,223,0,3,Mr. George Henry Green,male,51,0,0,21440,8.0500,S
223,224,0,3,Mr. Christo Nenkoff,male,0,0,0,349234,7.8958,S
224,225,1,1,Mr. Frederick Maxfield Hoyt,male,38,1,0,19943,90.0000,S
225,226,0,3,Mr. Karl Ivar Sven Berglund,male,22,0,0,PP4348,9.3500,S
226,227,1,2,Mr. William John Mellors,male,19,0,0,SWPP751,10.5000,S
227,228,0,3,"Mr. John Hall (""Henry"") Lovell",male,20,0,0,A521173,7.2500,S
228,229,0,2,Mr. Arne Jonas Fahlstrom,male,18,0,0,236171,13.0000,S
229,230,0,3,Miss. Mathilde Lefebre,female,0,3,1,4133,25.4667,S
230,231,1,1,Mrs. Henry Birkhardt (Irene Wallach) Harris,female,35,1,0,36973,83.4750,S
231,232,0,3,Mr. Bengt Edvin Larsson,male,29,0,0,347067,7.7750,S
232,233,0,2,Mr. Ernst Adolf Sjostedt,male,59,0,0,237442,13.5000,S
233,234,1,3,Miss. Lillian Gertrud Asplund,female,5,4,2,347077,31.3875,S
234,235,0,2,Mr. Robert William Norman Leyson,male,24,0,0,CA29566,10.5000,S
235,236,0,3,Miss. Alice Phoebe Harknett,female,0,0,0,WC6609,7.5500,S
236,237,0,2,Mr. Stephen Hold,male,44,1,0,26707,26.0000,S
237,238,1,2,"Miss. Marjorie ""Lottie"" Collyer",female,8,0,2,CA31921,26.2500,S
238,239,0,2,Mr. Frederick William Pengelly,male,19,0,0,28665,10.5000,S
239,240,0,2,Mr. George Henry Hunt,male,33,0,0,SCOW1585,12.2750,S
240,241,0,3,Miss. Thamine Zabour,female,0,1,0,2665,14.4542,C
241,242,1,3,"Miss. Katherine ""Kate"" Murphy",female,0,1,0,367230,15.5000,Q
242,243,0,2,Mr. Reginald Charles Coleridge,male,29,0,0,WC14263,10.5000,S
243,244,0,3,Mr. Matti Alexanteri Maenpaa,male,22,0,0,STONO23101275,7.1250,S
244,245,0,3,Mr. Sleiman Attalah,male,30,0,0,2694,7.2250,C
245,246,0,1,Dr. William Edward Minahan,male,44,2,0,19928,90.0000,Q
246,247,0,3,Miss. Agda Thorilda Viktoria Lindahl,female,25,0,0,347071,7.7750,S
247,248,1,2,Mrs. William (Anna) Hamalainen,female,24,0,2,250649,14.5000,S
248,249,1,1,Mr. Richard Leonard Beckwith,male,37,1,1,11751,52.5542,S
249,250,0,2,Rev. Ernest Courtenay Carter,male,54,1,0,244252,26.0000,S
250,251,0,3,Mr. James George Reed,male,0,0,0,362316,7.2500,S
251,252,0,3,Mrs. Wilhelm (Elna Matilda Persson) Strom,female,29,1,1,347054,10.4625,S
252,253,0,1,Mr. William Thomas Stead,male,62,0,0,113514,26.5500,S
253,254,0,3,Mr. William Arthur Lobb,male,30,1,0,A53336,16.1000,S
254,255,0,3,Mrs. Viktor (Helena Wilhelmina) Rosblom,female,41,0,2,370129,20.2125,S
255,256,1,3,Mrs. Darwis (Hanne Youssef Razi) Touma,female,29,0,2,2650,15.2458,C
256,257,1,1,Mrs. Gertrude Maybelle Thorne,female,0,0,0,PC17585,79.2000,C
257,258,1,1,Miss. Gladys Cherry,female,30,0,0,110152,86.5000,S
258,259,1,1,Miss. Anna Ward,female,35,0,0,PC17755,512.3292,C
259,260,1,2,Mrs. (Lutie Davis) Parrish,female,50,0,1,230433,26.0000,S
260,261,0,3,Mr. Thomas Smith,male,0,0,0,384461,7.7500,Q
261,262,1,3,Master. Edvin Rojj Felix Asplund,male,3,4,2,347077,31.3875,S
262,263,0,1,Mr. Emil Taussig,male,52,1,1,110413,79.6500,S
263,264,0,1,Mr. William Harrison,male,40,0,0,112059,0.0000,S
264,265,0,3,Miss. Delia Henry,female,0,0,0,382649,7.7500,Q
265,266,0,2,Mr. David Reeves,male,36,0,0,CA17248,10.5000,S
266,267,0,3,Mr. Ernesti Arvid Panula,male,16,4,1,3101295,39.6875,S
267,268,1,3,Mr. Ernst Ulrik Persson,male,25,1,0,347083,7.7750,S
268,269,1,1,Mrs. William Thompson (Edith Junkins) Graham,female,58,0,1,PC17582,153.4625,S
269,270,1,1,Miss. Amelia Bissette,female,35,0,0,PC17760,135.6333,S
270,271,0,1,Mr. Alexander Cairns,male,0,0,0,113798,31.0000,S
271,272,1,3,Mr. William Henry Tornquist,male,25,0,0,LINE,0.0000,S
272,273,1,2,Mrs. (Elizabeth Anne Maidment) Mellinger,female,41,0,1,250644,19.5000,S
273,274,0,1,Mr. Charles H Natsch,male,37,0,1,PC17596,29.7000,C
274,275,1,3,"Miss. Hanora ""Nora"" Healy",female,0,0,0,370375,7.7500,Q
275,276,1,1,Miss. Kornelia Theodosia Andrews,female,63,1,0,13502,77.9583,S
276,277,0,3,Miss. Augusta Charlotta Lindblom,female,45,0,0,347073,7.7500,S
277,278,0,2,"Mr. Francis ""Frank"" Parkes",male,0,0,0,239853,0.0000,S
278,279,0,3,Master. Eric Rice,male,7,4,1,382652,29.1250,Q
279,280,1,3,Mrs. Stanton (Rosa Hunt) Abbott,female,35,1,1,CA2673,20.2500,S
280,281,0,3,Mr. Frank Duane,male,65,0,0,336439,7.7500,Q
281,282,0,3,Mr. Nils Johan Goransson Olsson,male,28,0,0,347464,7.8542,S
282,283,0,3,Mr. Alfons de Pelsmaeker,male,16,0,0,345778,9.5000,S
283,284,1,3,Mr. Edward Arthur Dorking,male,19,0,0,A510482,8.0500,S
284,285,0,1,Mr. Richard William Smith,male,0,0,0,113056,26.0000,S
285,286,0,3,Mr. Ivan Stankovic,male,33,0,0,349239,8.6625,C
286,287,1,3,Mr. Theodore de Mulder,male,30,0,0,345774,9.5000,S
287,288,0,3,Mr. Penko Naidenoff,male,22,0,0,349206,7.8958,S
288,289,1,2,Mr. Masabumi Hosono,male,42,0,0,237798,13.0000,S
289,290,1,3,Miss. Kate Connolly,female,22,0,0,370373,7.7500,Q
290,291,1,1,"Miss. Ellen ""Nellie"" Barber",female,26,0,0,19877,78.8500,S
291,292,1,1,Mrs. Dickinson H (Helen Walton) Bishop,female,19,1,0,11967,91.0792,C
292,293,0,2,Mr. Rene Jacques Levy,male,36,0,0,SCParis2163,12.8750,C
293,294,0,3,Miss. Aloisia Haas,female,24,0,0,349236,8.8500,S

In [18]:
df1=df1.drop(df1[df1['Age'] == 0].index)

In [29]:
for x in df1.index:
    if df1.loc[x,'Embarked']== '':
     df1.drop(x,inplace=True)

In [32]:
df1=df1.dropna(subset=['Embarked'])

In [35]:
df1.to_csv(r'C:\Users\USER\OneDrive\Documents\pandas tutoriel\personal_data_cleaning.csv', index=False)

In [28]:
df1.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'first_name',
       'last_name', 'Full_name'],
      dtype='object')